#!/bin/bash
#SBATCH --nodes=1
#SBATCH --gres=gpu:8
#SBATCH --time=18:00:00
#SBATCH --mem-per-gpu=60000
#SBATCH --partition=alpha
#SBATCH --job-name=fused_features3
#SBATCH --mail-type=end
#SBATCH --mail-user=rajasekar.sankar@tu-dresden.de

module load release/23.04 Anaconda3
source $EBROOTANACONDA3/etc/profile.d/conda.sh
conda activate transCAL
cd /home/h5/rasa397c/Sankar/transfuser/tea_code_transfuser3
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python3 viz1.py --batch_size 100 --model_path /data/horse/ws/rasa397c-Sankar/transfuser/team_code_transfuser2/model_ckpt/models_2022/transfuser/model_seed3_37.pth --save_path /data/horse/ws/rasa397c-Sankar/Multimodal/transfuser/model_ckpt/job_fused_features_setting2_2workers_BS100_GPU8 --root_dir /data/horse/ws/rasa397c-Sankar/transfuser/data_mini --args_path /data/horse/ws/rasa397c-Sankar/transfuser/team_code_transfuser2/model_ckpt/models_2022/transfuser/args.txt
